# .github/workflows/logger.yaml
name: Code Commit PreProcessing
on:
  push:
    branches:
      - main
      
jobs:
   email-verification:
    name: "infoblox email id check"
    runs-on: ubuntu-latest
    steps:
      - name: email check
        env:
         user_email: ${{<>@infoblox.com}}
        if: success() && (endsWith( env.user_email, '<>@infoblox.com'))
        run: |
          echo "valid email id = <>@infoblox.com"
            
   github-preprocessing:
    name: "Code Commit Compliance Check"
    runs-on: ubuntu-latest
    needs: email-verification
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
           python-version: '3.8.10'
      - name: Install python dependencies
        run: |
          pip install requests
      - name: Commit Title Check
        env:
          TICKET_ID: Dummy_field
        run: |
          export TICKET_ID=$(python .github/scm_scripts/title_check.py '${{ github.event.head_commit.message }}')
          echo "TICKET_ID=$TICKET_ID" >> $GITHUB_ENV
      - name: Version1 Check
        env:
          V1_TOKEN: ${{ secrets.V1_TOKEN }}
        if: success() && (startsWith( env.TICKET_ID, 'TK-') || startsWith(env.TICKET_ID, 'B-'))
        run: |
          echo "V1 TICKE ID = ${{ env.TICKET_ID }}"
          python .github/scm_scripts/version_one_check.py "${{ env.TICKET_ID }}" "${{ env.V1_TOKEN }}"
      - name: JIRA Check
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        if: success() && (!startsWith(env.TICKET_ID, 'TK-') && !startsWith(env.TICKET_ID, 'B-'))
        run: |
          echo "JIRA TICKE ID = ${{ env.TICKET_ID }}"
          python .github/scm_scripts/jira_check.py "${{ env.TICKET_ID }}" "${{ env.JIRA_TOKEN }}"
